---
stages:
  #- pre-commit
  - build
  - test-urls
  - publish
  - trigger-upload

include:
  - project: saltstack/pop/cicd/ci-templates
    file: /docswork/url-tester-brok.yml

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID == null

variables:
  CICD_UPSTREAM_PATH: "saltstack/open/docs/salt-project-website"
  GIT_DEPTH: 1

the-hacks:
  stage: build
  image: python:3.11-slim
  script:
    - pip install -r tools/requirements.txt
    - mkdir -p content/the-hacks/
    - python tools/gen-the-hacks.py
    - cp tools/_index.md content/the-hacks/
  artifacts:
    paths:
      - content/the-hacks/

# Check URLs during publish stage in order to verify all URLs
# across The Hacks episodes
url-tester-brok:
  stage: publish

pages:
  stage: publish
  image: "${CI_TEMPLATE_REGISTRY_HOST}/pages/hugo:latest"
  script:
    # Generate site for hosting in GitLab Pages
    - hugo --buildFuture --baseURL "${CI_PAGES_URL}/"
    # Generate site for hosting on Salt Project Website
    - mkdir public-prod
    - hugo --baseURL "https://saltproject.io/" --destination ./public-prod
    # Provide useful console messages about both sites
    - 'echo "Gitlab Pages available at: ${CI_PAGES_URL}"'
    - 'echo "GitLab Pages source artifacts come from dir: public"'
    - 'echo "Prod website source artifacts come from dir: public-prod"'
  artifacts:
    paths:
      - public
      - public-prod

s3-upload:
  stage: trigger-upload
  tags:
    - gitlab-saltstack-salt-project-website-docker-machine
  image: debian:11-slim
  variables:
    CICD_S3_DEST_PATH: "saltproject-io-459849221361/"
  script:
    - test -n "${CICD_S3_DEST_PATH}"
    - echo "${CICD_S3_DEST_PATH}"
    - apt update && apt install awscli -y
    - aws s3 sync ${CI_PROJECT_DIR}/public-prod s3://${CICD_S3_DEST_PATH} --delete
    - aws cloudfront create-invalidation --distribution "E88P644XGB171" --paths "/*"
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG != null && $CI_PROJECT_PATH == $CICD_UPSTREAM_PATH'
      when: on_success
    - when: never

update-scheduled-pipeline:
  stage: trigger-upload
  image: debian:11-slim
  script:
    - |
      curl -fsSL \
        --request PUT \
        --header "PRIVATE-TOKEN: ${SALT_WEBSITE_SCHEDULE_TOKEN}" \
        --form ref="${CI_COMMIT_TAG}" \
        --form description="Republish site with latest The Hacks episodes" \
        --form cron="0 23 * * 2,5" \
        --form cron_timezone="UTC" \
        --form active="true" \
        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/pipeline_schedules/1463977"
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG != null && $CI_PROJECT_PATH == $CICD_UPSTREAM_PATH'
      when: on_success
    - when: never
