baseURL = "/"
title = "Salt Project"
languageCode = "en-us"
summaryLength = 10

[ taxonomies ]
    tag = 'tags'

[ the-hacks ]
    recommended = [
        "Shadow IT Makes the World Turn",
        'Red Hat To Restrict Source Code Access!',
        'Putting the "A.I. Genie" Back In The Bottle'
    ]
